In [0]:
import numpy
def MaxPool(myArr,row,col):
  maxnum = myArr[row][col]
  for i in range(2):
    for j in range(2):
      if(myArr[row+i][col+j] > maxnum):
        maxnum = myArr[row+i][col+j]
  return maxnum
rowsize = input().split("\n")[0]
while(len(rowsize) == 0):
  rowsize = input().split("\n")[0]
rowsize = int(rowsize)
halfrow = rowsize // 2
arr = numpy.random.random((rowsize,rowsize))
for i in range(rowsize):
  for j in range(rowsize):
    arr[i][j] = round(arr[i][j],2)
print(arr)
halfarr = numpy.zeros(shape=(halfrow,halfrow))
for i in range(halfrow):
  for j in range(halfrow):
    halfarr[i][j] = MaxPool(arr,2*i,2*j)
numpy.set_printoptions(precision=2)
print(halfarr)

8
[[0.82 0.51 0.75 0.06 0.55 0.07 0.7  0.98]
 [0.2  0.88 0.07 0.87 0.38 0.55 0.54 0.08]
 [0.55 0.07 0.23 0.71 0.93 0.63 0.72 0.38]
 [0.29 0.21 0.49 0.02 0.67 0.28 0.48 0.4 ]
 [0.88 0.56 0.7  0.63 0.99 0.39 0.96 0.11]
 [0.69 0.15 0.96 0.63 0.27 0.32 0.03 0.85]
 [0.29 0.02 0.39 0.91 1.   0.23 0.85 0.44]
 [0.51 0.54 0.45 0.18 0.74 0.58 0.78 0.08]]
[[0.88 0.87 0.55 0.98]
 [0.55 0.71 0.93 0.72]
 [0.88 0.96 0.99 0.96]
 [0.54 0.91 1.   0.85]]
